---
- name: Ensure dependencies installed
  apt:
    name:
      - git
      - npm
    state: present
    update_cache: yes

- name: Clone or update WiFi Manager repo
  become_user: "{{ app_user }}"
  git:
    repo: "{{ repo_url }}"
    dest: "{{ app_dir }}"
    version: main
    force: yes

- name: Install PM2 globally
  npm:
    name: pm2
    global: yes
    state: present

- name: Start backend with PM2
  become_user: "{{ app_user }}"
  shell: |
    cd {{ app_dir }}/backend
    pm2 start wifi-client.py --interpreter python3 --name wifi-backend || pm2 restart wifi-backend
    pm2 save

- name: Ensure PM2 frontend is clean
  become_user: "{{ app_user }}"
  shell: pm2 delete wifi-frontend || true

- name: Start frontend with PM2 (use absolute paths)
  become_user: "{{ app_user }}"
  shell: |
    cd {{ app_dir }}/frontend
    /usr/bin/npx serve -s dist -l 3000
    pm2 start /usr/bin/npx --name wifi-frontend -- serve -s dist -l 3000
    pm2 save

